### ISSUE TITLE
How to get the link and the span on the same line so that every time I press the button, it skips a line and  put the down the link and the printed text on the same line.

### ISSUE THREAD

**Issue by JRProgramming** [JRProgramming/johnny#13]
`<a href = # id="linker"></a><span id="cooler"></span>
<input type="button" value="Click Me" onclick="doit()">
<script>
function doit(){
var johnny = document.createElement("P")
var george = document.createTextNode("Johnny")
johnny.appendChild(george)
var ramirez = document.createElement("P");
var curious = document.createTextNode("Bobby");
ramirez.appendChild(curious);
document.getElementById("linker").appendChild(johnny)
documet.getElementById("cooler").appendChild(johnny)
}
</script>`

**Comment by Allen-B1** [comment]
Also I think you should change `<p>` to `<div>` so that it's not double spaced.
