### ISSUE TITLE
How come when I visit the site it redirects

### ISSUE THREAD

**Issue by Allen-B1** [JRProgramming/johnny#6]
When I visit the [site](https://jrprogramming.github.io/johnny/HTML%20Code.html) it redirects me to jrsocialnetworksite.com

**Comment by JRProgramming** [comment]
I made a mistake with it. I created a new domain name but the domain name isn't registered so I have to redo the whole thing again, I'll tell you when it is working.

**Comment by Allen-B1** [comment]
OK, I'll close.
